name: Customer Segmentation Pipeline

# Workflow ini akan berjalan otomatis setiap kali 'git push' ke branch utama (main/master)
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    # 1. Menyamakan nama dengan gambar
    - name: Run actions/checkout@v3
      uses: actions/checkout@v4

    # 2. Menyiapkan environment Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Menambahkan tahap Check Env
    - name: Check Env
      run: |
        python --version
        pip --version

    # 4. Menyamakan nama dan menginstal dependencies 
    - name: Install dependencies
      run: |
        pip install pandas scikit-learn mlflow numpy joblib

    # 5. Menjalankan script ML
    - name: Run mlflow project
      run: |
        mlflow run MLProject --env-manager=local --experiment-name="Submission Membangun Sistem Machine Learning - KMeans Clustering"

    # 6. Menambahkan tahap Run ID 
    - name: Get latest MLflow run_id
      run: |
        python -c "
        import mlflow
        import os
        
        db_path = os.path.abspath('MLProject/mlflow.db')
        mlflow.set_tracking_uri(f'sqlite:///{db_path}')
        
        runs = mlflow.search_runs(experiment_names=['Submission Membangun Sistem Machine Learning - KMeans Clustering'])
        if not runs.empty:
            print(f'Latest MLflow Run ID: {runs.iloc[0].run_id}')
        else:
            print('Run ID tidak ditemukan.')
        "

    # 7. Build Docker Image 
    - name: Test Docker Build
      run: |
        cd MLProject
        docker build -t test-segmentation-image:latest .

    # 8. Menyimpan Artefak Data Bersih & Model
    - name: Upload Preprocessed Artifacts and Model
      uses: actions/upload-artifact@v4
      with:
        name: customer-segmentation-artifacts
        path: |
          MLProject/shopping_trends_preprocessed.csv
          MLProject/model/kmeans_model.joblib
        retention-days: 7
